### ISSUE TITLE
Pb affichage version du 31/01/2021

### ISSUE THREAD

**Issue by net1957** [lunarok/jeedom_heliotrope#31]
après mise à jour du plugin, l'affichage est le suivant:
![image](https://user-images.githubusercontent.com/17736/155285867-82987661-5d12-4204-acc8-10c3fc92e31d.png)

en agrandissant la taille du cadre, la courbe grossi plus que prévu:
![image](https://user-images.githubusercontent.com/17736/155286070-8c129543-bd4d-49e4-865a-b9aec8af696b.png)

et la seule solution pour retrouver une courbe complete est de desactiver l'affichage (Altitude du soleil), puis de le reactiver.

Cela empeche aussi l'affichage simultané de la rose des vents avec cette courbe.

Je tourne sur Jeedom 4.2.12 sur Pi4 (raspian/debian 10.11)

**Comment by dough29** [comment]
Même constat ici

**Comment by lunarok** [comment]
Retours à faire sur le forum Jeedom svp

**Comment by jpty** [comment]
La rose des vents est prévue uniquement sous la courbe.
La courbe prend toujours toute la largeur de la tuile. Sa hauteur est un ratio de la largeur.

Il suffit d'augmenter la hauteur de la tuile.
