### ISSUE TITLE
Supprimer une commande

### ISSUE THREAD

**Issue by Ethal** [lunarok/jeedom_heliotrope#8]
Bonjour,

Est tu ok pour  supprimer la possibilité de supprimer une commande, 
je pense que ce n'est pas utile , si on la supprime ,elle sera re créer si on sauvegarde l'equipment, mais elle n'aura pas le meme id, donc si utilisée(scenario,virtuel,..) précédemment ailleurs cela va poser problème.
 
il faut juste enlever la ligne suivante du fichier heliotrope.js
tr += '<i class="fa fa-minus-circle pull-right cmdAction cursor" data-action="remove"></i></td>';

si oui , je te propose de le faire pour ce plugin et pour les plugins PlayTTS et Vigillance meteo également.

Cordialement,

**Comment by lunarok** [comment]
Ah oui, la suppression est pas utile c'est sur, si tu fais les PR pas de soucis

**Comment by Ethal** [comment]
Bonjour,

ou alors rajouter la classe "expertModeVisible", comme pour l'option de config(roue crantée)
mais  je pense que la plupart des utilisateurs sont en mode expert ,

je te laisse choisir , 
et je m'occupe des 3 plugins cités dans mon premier message.

Cordialement,

**Comment by lunarok** [comment]
Oui beaucoup sont en mode expert, même là ca reste que la commande sera recréer directement. Donc ok pour la suppression du bouton directement

**Comment by Ethal** [comment]
Bonjour,
j'ai fait le PR pour les plugins VigilanceMeteo, heliotrope et playTTS
